// non api calls
export const LOGOUT_USER = 'LOGOUT_USER';

// api calls - request
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const ADD_RESOURCE_REQUEST = 'ADD_RESOURCE_REQUEST';
export const DELETE_RESOURCE_REQUEST = 'DELETE_RESOURCE_REQUEST';

// api calls - success
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';

// api calls - failure
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const ADD_RESOURCE_FAILURE = 'ADD_RESOURCE_FAILURE';
export const DELETE_RESOURCE_FAILURE = 'DELETE_RESOURCE_FAILURE';
